
MethodLength:
  Max: 200

LineLength:
  Max: 160

AbcSize:
  Max: 100

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

# safe navigation was introduced in ruby 2.3
Style/SafeNavigation:
  Enabled: false

# match?() was added in ruby 2.4
#Performance/RegexpMatch:
#  Enabled: false


# TODO: figure out which to use `Date` or `Time`
Style/DateTime:
  Enabled: false


# testing can be slow
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'test/**/*.rb'
